// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcVm82M0Lf3pmJsg6Tbrlj3EoGKn_nFDs',
    appId: '1:1026732915869:web:0d2193ee63110de1386874',
    messagingSenderId: '1026732915869',
    projectId: 'flutterauthen-34d4b',
    authDomain: 'flutterauthen-34d4b.firebaseapp.com',
    storageBucket: 'flutterauthen-34d4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHyj-OdMK_xXkA8acL54RdfVhGPjUayws',
    appId: '1:1026732915869:android:31aa1d8a2592e3e1386874',
    messagingSenderId: '1026732915869',
    projectId: 'flutterauthen-34d4b',
    storageBucket: 'flutterauthen-34d4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB6Bbzyb85Q7jNRM-BEAQYENcRDCnNeUc',
    appId: '1:1026732915869:ios:2893be0c7687a5c8386874',
    messagingSenderId: '1026732915869',
    projectId: 'flutterauthen-34d4b',
    storageBucket: 'flutterauthen-34d4b.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB6Bbzyb85Q7jNRM-BEAQYENcRDCnNeUc',
    appId: '1:1026732915869:ios:8953e3f3888e14ac386874',
    messagingSenderId: '1026732915869',
    projectId: 'flutterauthen-34d4b',
    storageBucket: 'flutterauthen-34d4b.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
